home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
    path('contact/', views.contact, name='contact'),
    path('gallery/', views.gallery, name='gallery'),
]

story3/urls.py
from django.contrib import admin
from django.urls import path, include
from home import views

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render

# Create your views here.

def home(request):
    return render(request, 'home.html')

def contact(request):
    return render(request, 'contact.html')

def gallery(request):
    return render(request, 'gallery.html')

home/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" style=""><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    
    <meta n="" ame="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="icon" type="image/png" href="{% static 'images/favicon.png' %}">
    <script src="{% static 'script/script.js' %}"></script>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,700&display=swap" rel="stylesheet">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <title>{% block title %}WELCOME | Farizio Kautsar Heruzy{% endblock %}</title>
</head>

<body>
    <nav class="navbar navbar-expand-sm navbar-custom justify-content-center fixed-top" style="box-shadow: 0px 10px 20px rgba(0, 0, 0, 0.15);">
        <ul class="navbar-nav">
            <li class="nav-item" style = "margin-right: 4vw">
            <a class="nav-link" href="{% url 'home:gallery' %}">GALLERY</a>
            </li>
            <li class="nav-item" >
            <a class="nav-link" href="{% url 'home:home' %}">HOME</a>
            </li>
            <li class="nav-item" style = "margin-left: 4vw">
            <a class="nav-link" href="{% url 'home:contact' %}">CONTACT ME</a>
            </li>
        </ul>
    </nav>

    {% block body %}
    {% endblock %}
</body>

home/templates/contact.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
CONTACT | Farizio Kautsar Heruzy
{% endblock %}
{% block body %}
    <div class = "page">
        <div class = "sidebyside">
            <div class = "head_left">          
                <div class = "page_phone">
                    <div class = "line" style="margin-bottom: 2vw;">
                    </div>
                    <div>
                        <a id = "like">Like</a>
                        <a class = "button" href="{% url 'home:gallery' %}" style = "color: black">my stuffs?</a>
                    </div>
                    <div style = "height: 4vw">

                        </div>
                    <p class = "findme">
                        You can find me on:
                    </p>
                    <div style = "height: 2vw">

                        </div>
                    <div class = "row_class">
                        <a  href="https://api.whatsapp.com/send?phone=6281282100255">
                            <img class = "contact_icons" src="{% static 'images/contact_icons/whatsapp.svg' %}"></img>
                        </a>
                        <a  href="https://www.instagram.com/ziokautsar/">
                            <img class = "contact_icons" src="{% static 'images/contact_icons/instagram.svg' %}"></img>
                        </a>
                        <a  href="https://www.linkedin.com/in/farizio-kautsar-655844126/">
                            <img class = "contact_icons" src="{% static 'images/contact_icons/linkedin.svg' %}"></img>
                        </a>
                        <a  href="https://twitter.com/farizio_kautsar">
                            <img class = "contact_icons" src="{% static 'images/contact_icons/twitter.svg' %}"></img>
                        </a>
                    </div>
                    <div style = "height: 4vw">

                        </div>
                    <div class = "row_class">
                        <img src = "{% static 'images/icons/email.svg' %}" class = "contact_emailphone">
                        </img>
                        <p class = "contact_emailphone_text"">
                            kheruzy@gmail.com
                        </p>
                        <div style = "width: 45px"></div>
                        <img src = "{% static 'images/icons/phone.svg' %}" class = "contact_emailphone">
                        </img>
                        <p class = "contact_emailphone_text"">
                            +62 812 8210 0255
                        </p>
                    </div>
                    <div style = "height: 60px">

                        </div>
                    <div class = "line">
                    </div>
                    <p id = "excited">
                        I'm excited to be a part of your next big project
                    </p>
                    <div style = "height: 4vw"></div>
                    <a class = "button" href="{% url 'home:home' %}">
                        BACK HOME
                    </a>
                </div>
            </div>
            <div class = "head_right" id="contact">
                <img src="{% static 'images/contact_side.jpg' %}" class="pic_phone"></img>
            </div>
        </div>
    </div>
    <!-- <div class = "whatido_background"> -->
        
    </div>
    <!-- <div class = "programs_background"> -->
        
    </div>
    <!-- <div class = "languages_background"> -->
        
    </div>
{% endblock %}

home/templates/gallery.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
GALLERY | Farizio Kautsar Heruzy
{% endblock %}
{% block body %}
    <div class = "page">
            
            <p class = "oneline">
                Find what you like
            </p>
            <div class = "line">
                </div>
            <p style = "font-size: calc(0.1rem + 0.5vw); color:#AEAEAE">
                    *DUMMY ARTS*
                </p>
            <div style = "height: 60px">

                </div>
        <div class = "column_class">
            <div class = "row_class">
                <a class = "artwork_frame" >
                    <img src = "https://images.unsplash.com/photo-1499781350541-7783f6c6a0c8?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=815&q=80" style="width: 100%;"></img>
                </a>
                <div style = "width: 60px">
                </div>
                <a class = "artwork_frame">
                    <img src = "https://images.unsplash.com/photo-1526304760382-3591d3840148?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80" style="width: 100%;"></img>
                </a>
                <div style = "width: 60px">
                </div>
                <a class = "artwork_frame">
                    <img src = "https://images.unsplash.com/photo-1484589065579-248aad0d8b13?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=396&q=80" style="width: 100%;"></img>
                </a>
            </div>
            <div style = "height: 20px">
            </div>
            <div class = "row_class">
                <a class = "artwork_frame" >
                    <img src = "https://images.unsplash.com/photo-1551913902-c92207136625?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=334&q=80" style="width: 100%;"></img>
                </a>
                <div style = "width: 60px">
                </div>
                <a class = "artwork_frame" >
                    <img src = "https://images.unsplash.com/photo-1554188248-986adbb73be4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80" style="width: 100%;"></img>
                </a>
                <div style = "width: 60px">
                </div>
                <a class = "artwork_frame" >
                    <img src = "https://images.unsplash.com/photo-1549490349-8643362247b5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=334&q=80" style="width: 100%;"></img>
                </a>
            </div>
            <div style = "height: 20px">
                </div>
            <div class = "row_class">
                <a class = "artwork_frame" >
                    <img src = "https://images.unsplash.com/photo-1549887534-1541e9326642?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=401&q=80" style="width: 100%;"></img>
                </a>
                <div style = "width: 60px">
                </div>
                <a class = "artwork_frame">
                    <img src = "https://images.unsplash.com/photo-1482160549825-59d1b23cb208?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80" style="width: 100%;"></img>
                </a>
                <div style = "width: 60px">
                </div>
                <a class = "artwork_frame" >
                    <img src = "https://images.unsplash.com/photo-1493210977798-4f655ac200a9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=562&q=80" style="width: 100%;"></img>
                </a>
            </div>
        </div>
        <div style = "height: 150px">

        </div>
        <div style="text-align: center; font-weight: 700;">
            <p class ="oneline">Like what you see?</p>
            <div style = "height: 60px">

                </div>
            <div class="line">

                </div>
        </div>
        <div style = "height: 60px">

        </div>
        <!-- BUTTON CONTACT ME -->
        <div style="text-align: center; ">
            <a class = "button" href="{% url 'home:contact' %}">
                RING ME
            </a>
        </div>
        <div style = "height: 300px">

        </div>
    </div>
{% endblock %}